#!/bin/bash

# args:
# - ORG (docker-hub username)
# - PW (docker-hub password)
# - IMG (image to delete)

ORG='...'
PW='.......'
IMG='node-app'

# get token
echo 'Retrieving token ...'
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${ORG}'", "password": "'${PW}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

echo "token: $TOKEN for ${ORG}"

curl -X DELETE -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${ORG}/${IMG}
echo 'DELETED'
